export const COUNTRY_MAP: Record<string, string> = {
  "Afghanistan": "AFG", "Albania": "ALB", "Algeria": "DZA", "Andorra": "AND", "Angola": "AGO",
  "Argentina": "ARG", "Armenia": "ARM", "Australia": "AUS", "Austria": "AUT", "Azerbaijan": "AZE",
  "Bahamas": "BHS", "Bahrain": "BHR", "Bangladesh": "BGD", "Barbados": "BRB", "Belarus": "BLR",
  "Belgium": "BEL", "Belize": "BLZ", "Benin": "BEN", "Bhutan": "BTN", "Bolivia": "BOL",
  "Bosnia and Herzegovina": "BIH", "Botswana": "BWA", "Brazil": "BRA", "Brasil": "BRA", "Brésil": "BRA", "Brunei": "BRN",
  "Bulgaria": "BGR", "Burkina Faso": "BFA", "Burundi": "BDI", "Cambodia": "KHM", "Cameroon": "CMR",
  "Canada": "CAN", "Central African Republic": "CAF", "Chad": "TCD", "Chile": "CHL", "China": "CHN", "Chine": "CHN", "PRC": "CHN",
  "Colombia": "COL", "Comoros": "COM", "Congo": "COG", "Costa Rica": "CRI", "Croatia": "HRV",
  "Cuba": "CUB", "Cyprus": "CYP", "Czech Republic": "CZE", "Czechia": "CZE", "Denmark": "DNK", "Djibouti": "DJI",
  "Dominica": "DMA", "Dominican Republic": "DOM", "Ecuador": "ECU", "Egypt": "EGY", "El Salvador": "SLV",
  "Equatorial Guinea": "GNQ", "Eritrea": "ERI", "Estonia": "EST", "Eswatini": "SWZ", "Ethiopia": "ETH",
  "Fiji": "FJI", "Finland": "FIN", "France": "FRA", "Francia": "FRA", "Frankreich": "FRA", "Gabon": "GAB", "Gambia": "GMB", "Georgia": "GEO",
  "Germany": "DEU", "Deutschland": "DEU", "Alemania": "DEU", "Allemagne": "DEU", "Ghana": "GHA", "Greece": "GRC", "Grenada": "GRD", "Guatemala": "GTM",
  "Guinea": "GIN", "Guinea-Bissau": "GNB", "Guyana": "GUY", "Haiti": "HTI", "Honduras": "HND",
  "Hungary": "HUN", "Iceland": "ISL", "India": "IND", "Indonesia": "IDN", "Iran": "IRN",
  "Iraq": "IRQ", "Ireland": "IRL", "Israel": "ISR", "Italy": "ITA", "Italia": "ITA", "Italien": "ITA", "Italie": "ITA", "Ivory Coast": "CIV",
  "Jamaica": "JAM", "Japan": "JPN", "Japón": "JPN", "Japon": "JPN", "Jordan": "JOR", "Kazakhstan": "KAZ", "Kenya": "KEN",
  "Kiribati": "KIR", "Korea": "KOR", "South Korea": "KOR", "S. Korea": "KOR", "North Korea": "PRK", "N. Korea": "PRK", "Kuwait": "KWT", "Kyrgyzstan": "KGZ", "Laos": "LAO",
  "Latvia": "LVA", "Lebanon": "LBN", "Lesotho": "LSO", "Liberia": "LBR", "Libya": "LBY",
  "Liechtenstein": "LIE", "Lithuania": "LTU", "Luxembourg": "LUX", "Madagascar": "MDG",
  "Malawi": "MWI", "Malaysia": "MYS", "Maldives": "MDV", "Mali": "MLI", "Malta": "MLT",
  "Mauritania": "MRT", "Mauritius": "MUS", "Mexico": "MEX", "México": "MEX", "Mexique": "MEX", "Micronesia": "FSM", "Moldova": "MDA",
  "Monaco": "MCO", "Mongolia": "MNG", "Montenegro": "MNE", "Morocco": "MAR", "Mozambique": "MOZ",
  "Myanmar": "MMR", "Namibia": "NAM", "Nauru": "NRU", "Nepal": "NPL", "Netherlands": "NLD", "Holland": "NLD",
  "New Zealand": "NZL", "NZ": "NZL", "Nicaragua": "NIC", "Niger": "NER", "Nigeria": "NGA", "North Macedonia": "MKD",
  "Norway": "NOR", "Oman": "OMN", "Pakistan": "PAK", "Palau": "PLW", "Palestine": "PSE",
  "Panama": "PAN", "Papua New Guinea": "PNG", "Paraguay": "PRY", "Peru": "PER", "Philippines": "PHL",
  "Poland": "POL", "Portugal": "PRT", "Qatar": "QAT", "Romania": "ROU", "Russia": "RUS", "Russian Federation": "RUS", "Rusia": "RUS", "Russie": "RUS", "Russland": "RUS",
  "Rwanda": "RWA", "Samoa": "WSM", "San Marino": "SMR", "Saudi Arabia": "SAU", "Saudi": "SAU", "Senegal": "SEN",
  "Serbia": "SRB", "Seychelles": "SYC", "Sierra Leone": "SLE", "Singapore": "SGP", "Slovakia": "SVK",
  "Slovenia": "SVN", "Solomon Islands": "SLB", "Somalia": "SOM", "South Africa": "ZAF", "S. Africa": "ZAF",
  "South Sudan": "SSD", "Spain": "ESP", "España": "ESP", "Spanien": "ESP", "Espagne": "ESP", "Sri Lanka": "LKA", "Sudan": "SDN", "Suriname": "SUR",
  "Sweden": "SWE", "Switzerland": "CHE", "Swiss": "CHE", "Syria": "SYR", "Taiwan": "TWN", "Tajikistan": "TJK",
  "Tanzania": "TZA", "Thailand": "THA", "Togo": "TGO", "Tonga": "TON", "Trinidad and Tobago": "TTO",
  "Tunisia": "TUN", "Turkey": "TUR", "Türkiye": "TUR", "Turkmenistan": "TKM", "Tuvalu": "TUV", "Uganda": "UGA",
  "Ukraine": "UKR", "United Arab Emirates": "ARE", "UAE": "ARE", "U.A.E.": "ARE", "Emiratos Árabes": "ARE", "United Kingdom": "GBR", "UK": "GBR", "U.K.": "GBR", "Great Britain": "GBR", "Royaume-Uni": "GBR", "Großbritannien": "GBR", "Reino Unido": "GBR", "United States": "USA", "USA": "USA", "U.S.": "USA", "U.S.A.": "USA", "America": "USA", "Estados Unidos": "USA", "États-Unis": "USA", "Vereinigte Staaten": "USA",
  "Uruguay": "URY", "Uzbekistan": "UZB", "Vanuatu": "VUT", "Venezuela": "VEN", "Vietnam": "VNM", "Viet Nam": "VNM",
  "Yemen": "YEM", "Zambia": "ZMB", "Zimbabwe": "ZWE"
};

export const US_STATES: Record<string, string> = {
  "Alabama": "USA", "Alaska": "USA", "Arizona": "USA", "Arkansas": "USA", "California": "USA",
  "Colorado": "USA", "Connecticut": "USA", "Delaware": "USA", "Florida": "USA", "Georgia": "USA",
  "Hawaii": "USA", "Idaho": "USA", "Illinois": "USA", "Indiana": "USA", "Iowa": "USA",
  "Kansas": "USA", "Kentucky": "USA", "Louisiana": "USA", "Maine": "USA", "Maryland": "USA",
  "Massachusetts": "USA", "Michigan": "USA", "Minnesota": "USA", "Mississippi": "USA", "Missouri": "USA",
  "Montana": "USA", "Nebraska": "USA", "Nevada": "USA", "New Hampshire": "USA", "New Jersey": "USA",
  "New Mexico": "USA", "New York": "USA", "North Carolina": "USA", "North Dakota": "USA", "Ohio": "USA",
  "Oklahoma": "USA", "Oregon": "USA", "Pennsylvania": "USA", "Rhode Island": "USA", "South Carolina": "USA",
  "South Dakota": "USA", "Tennessee": "USA", "Texas": "USA", "Utah": "USA", "Vermont": "USA",
  "Virginia": "USA", "Washington": "USA", "West Virginia": "USA", "Wisconsin": "USA", "Wyoming": "USA"
};

export const WORLD_CITIES: Record<string, string> = {
  "London": "GBR", "Paris": "FRA", "Berlin": "DEU", "Madrid": "ESP", "Rome": "ITA",
  "Moscow": "RUS", "Tokyo": "JPN", "Beijing": "CHN", "Seoul": "KOR", "Bangkok": "THA",
  "Singapore": "SGP", "Jakarta": "IDN", "Mumbai": "IND", "Delhi": "IND", "Cairo": "EGY",
  "Lagos": "NGA", "Nairobi": "KEN", "Johannesburg": "ZAF", "New York": "USA", "Los Angeles": "USA",
  "Chicago": "USA", "Toronto": "CAN", "Mexico City": "MEX", "Sao Paulo": "BRA", "Buenos Aires": "ARG",
  "Sydney": "AUS", "Melbourne": "AUS", "Auckland": "NZL", "Dubai": "ARE", "Riyadh": "SAU",
  "Istanbul": "TUR", "Tel Aviv": "ISR", "Jerusalem": "ISR", "Gaza": "PSE", "Beirut": "LBN",
  "Damascus": "SYR", "Baghdad": "IRQ", "Tehran": "IRN", "Kabul": "AFG", "Islamabad": "PAK",
  "Kyiv": "UKR", "Warsaw": "POL", "Prague": "CZE", "Vienna": "AUT", "Brussels": "BEL",
  "Amsterdam": "NLD", "Stockholm": "SWE", "Oslo": "NOR", "Copenhagen": "DNK", "Helsinki": "FIN",
  "Lisbon": "PRT", "Athens": "GRC", "Washington": "USA", "San Francisco": "USA", "Miami": "USA",
  "Houston": "USA", "Vancouver": "CAN", "Montreal": "CAN", "Ottawa": "CAN", "Hong Kong": "HKG",
  "Taipei": "TWN", "Shanghai": "CHN", "Manila": "PHL", "Ho Chi Minh City": "VNM",
  "Abidjan": "CIV", "Abu Dhabi": "ARE", "Accra": "GHA", "Addis Ababa": "ETH", "Adelaide": "AUS",
  "Algiers": "DZA", "Almaty": "KAZ", "Amman": "JOR", "Ankara": "TUR", "Antananarivo": "MDG",
  "Antwerp": "BEL", "Asuncion": "PRY", "Atlanta": "USA", "Austin": "USA",
  "Baku": "AZE", "Baltimore": "USA", "Bamako": "MLI", "Bandung": "IDN", "Bangalore": "IND",
  "Barcelona": "ESP", "Barranquilla": "COL", "Basra": "IRQ", "Belo Horizonte": "BRA", "Belgrade": "SRB",
  "Bishkek": "KGZ", "Birmingham": "GBR", "Bogota": "COL", "Boston": "USA", "Brasilia": "BRA",
  "Bratislava": "SVK", "Brazzaville": "COG", "Brisbane": "AUS", "Bucharest": "ROU", "Budapest": "HUN",
  "Bursa": "TUR", "Busan": "KOR", "Calgary": "CAN", "Cali": "COL", "Cape Town": "ZAF",
  "Caracas": "VEN", "Casablanca": "MAR", "Chengdu": "CHN", "Chennai": "IND", "Chiba": "JPN",
  "Chisinau": "MDA", "Chittagong": "BGD", "Chongqing": "CHN", "Cleveland": "USA", "Cologne": "DEU",
  "Colombo": "LKA", "Conakry": "GIN", "Cordoba": "ARG", "Curitiba": "BRA", "Da Nang": "VNM",
  "Dakar": "SEN", "Dalian": "CHN", "Dallas": "USA", "Dar es Salaam": "TZA", "Davao City": "PHL",
  "Denver": "USA", "Detroit": "USA", "Dhaka": "BGD", "Doha": "QAT", "Donetsk": "UKR",
  "Dortmund": "DEU", "Douala": "CMR", "Durban": "ZAF", "Dushanbe": "TJK", "Erbil": "IRQ",
  "Essen": "DEU", "Faisalabad": "PAK", "Fortaleza": "BRA", "Frankfurt": "DEU", "Fukuoka": "JPN",
  "Fuzhou": "CHN", "Gaborone": "BWA", "Genoa": "ITA", "George Town": "MYS", "Giza": "EGY",
  "Glasgow": "GBR", "Goiania": "BRA", "Guadalajara": "MEX", "Guangzhou": "CHN", "Guatemala City": "GTM",
  "Guayaquil": "ECU", "Guiyang": "CHN", "Gwangju": "KOR", "Haifa": "ISR", "Hamburg": "DEU",
  "Hanoi": "VNM", "Harare": "ZWE", "Harbin": "CHN", "Havana": "CUB", "Hefei": "CHN",
  "Hiroshima": "JPN", "Homs": "SYR", "Hsinchu": "TWN", "Hyderabad": "IND", "Ibadan": "NGA",
  "Incheon": "KOR", "Isfahan": "IRN", "Izmir": "TUR", "Jaipur": "IND", "Jeddah": "SAU",
  "Jinan": "CHN", "Jinzhong": "CHN", "Jodhpur": "IND", "Kaohsiung": "TWN",
  "Karachi": "PAK", "Karlsruhe": "DEU", "Kathmandu": "NPL", "Kawasaki": "JPN", "Kazan": "RUS",
  "Kharkiv": "UKR", "Khartoum": "SDN", "Kigali": "RWA", "Kingston": "JAM",
  "Kinshasa": "COD", "Kitakyushu": "JPN", "Kobe": "JPN", "Kolkata": "IND", "Kota Kinabalu": "MYS",
  "Kowloon": "HKG", "Krakow": "POL", "Kuala Lumpur": "MYS", "Kumasi": "GHA", "Kunming": "CHN",
  "Kuwait City": "KWT", "Kyoto": "JPN", "La Paz": "BOL", "Lahore": "PAK", "Lanzhou": "CHN",
  "Las Vegas": "USA", "Leeds": "GBR", "Leipzig": "DEU", "Libreville": "GAB", "Lille": "FRA",
  "Lima": "PER", "Linz": "AUT", "Liverpool": "GBR", "Ljubljana": "SVN", "Lome": "TGO",
  "Luanda": "AGO", "Lubumbashi": "COD", "Lucknow": "IND", "Lusaka": "ZMB", "Luxembourg City": "LUX",
  "Lyon": "FRA", "Maceio": "BRA", "Madinah": "SAU", "Makassar": "IDN", "Malabo": "GNQ",
  "Malaga": "ESP", "Male": "MDV", "Managua": "NIC", "Manaus": "BRA", "Mandalay": "MMR", "Maputo": "MOZ", "Maracaibo": "VEN", "Marrakech": "MAR", "Marseille": "FRA",
  "Mashhad": "IRN", "Mbabane": "SWZ", "Medan": "IDN", "Medellin": "COL", "Mecca": "SAU",
  "Medina": "SAU", "Mekka": "SAU", "Memphis": "USA", "Mendoza": "ARG",
  "Mexicali": "MEX", "Milan": "ITA", "Milwaukee": "USA", "Minneapolis": "USA", "Minsk": "BLR",
  "Mogadishu": "SOM", "Mombasa": "KEN", "Monterrey": "MEX", "Montevideo": "URY", "Montpellier": "FRA",
  "Munich": "DEU", "Muscat": "OMN", "Nagoya": "JPN", "Nagpur": "IND", "Naha": "JPN",
  "Nanchang": "CHN", "Nanjing": "CHN", "Nanning": "CHN", "Naples": "ITA", "Nashville": "USA",
  "Nassau": "BHS", "Ndjamena": "TCD", "New Orleans": "USA", "Niamey": "NER", "Nice": "FRA",
  "Nicosia": "CYP", "Ningbo": "CHN", "Nizhny Novgorod": "RUS", "Nouakchott": "MRT", "Novosibirsk": "RUS",
  "Nuku'alofa": "TON", "Nur-Sultan": "KAZ", "Oakland": "USA", "Odessa": "UKR", "Okinawa": "JPN",
  "Oklahoma City": "USA", "Omaha": "USA", "Omsk": "RUS", "Oran": "DZA", "Orlando": "USA",
  "Osaka": "JPN", "Ouagadougou": "BFA", "Palembang": "IDN", "Palermo": "ITA", "Panama City": "PAN",
  "Paramaribo": "SUR", "Patna": "IND", "Patras": "GRC", "Pattaya": "THA", "Peshawar": "PAK",
  "Philadelphia": "USA", "Phnom Penh": "KHM", "Phoenix": "USA", "Piraeus": "GRC", "Pittsburgh": "USA",
  "Podgorica": "MNE", "Port Louis": "MUS", "Port Moresby": "PNG", "Port of Spain": "TTO", "Port-au-Prince": "HTI",
  "Porto": "PRT", "Porto Alegre": "BRA", "Porto-Novo": "BEN", "Portsmouth": "GBR",
  "Poznan": "POL", "Pretoria": "ZAF", "Pristina": "SRB", "Puebla": "MEX", "Pune": "IND",
  "Pyongyang": "PRK", "Quebec City": "CAN", "Quito": "ECU", "Rabat": "MAR", "Rawalpindi": "PAK",
  "Recife": "BRA", "Reykjavik": "ISL", "Riga": "LVA", "Rio de Janeiro": "BRA", "Rosario": "ARG",
  "Rostov-on-Don": "RUS", "Rotterdam": "NLD", "Sacramento": "USA", "Saint Petersburg": "RUS", "Salzburg": "AUT",
  "Samara": "RUS", "San Antonio": "USA", "San Diego": "USA", "San Salvador": "SLV", "Sanaa": "YEM", "Santa Cruz": "BOL", "Santiago": "CHL", "Santo Domingo": "DOM",
  "Sapporo": "JPN", "Sarajevo": "BIH", "Seattle": "USA", "Semarang": "IDN", "Sendai": "JPN",
  "Seville": "ESP", "Sfax": "TUN", "Shantou": "CHN", "Sharjah": "ARE", "Sheffield": "GBR",
  "Shenyang": "CHN", "Shenzhen": "CHN", "Shijiazhuang": "CHN", "Shiraz": "IRN", "Shizuoka": "JPN",
  "Skopje": "MKD", "Sofia": "BGR", "St. Louis": "USA", "Stavropol": "RUS", "Strasbourg": "FRA",
  "Stuttgart": "DEU", "Sucre": "BOL", "Surabaya": "IDN", "Surat": "IND", "Suva": "FJI",
  "Suzhou": "CHN", "Tabriz": "IRN", "Taichung": "TWN", "Tainan": "TWN", "Tallinn": "EST",
  "Tangier": "MAR", "Tashkent": "UZB", "Tegucigalpa": "HND",
  "The Hague": "NLD", "Thessaloniki": "GRC", "Thimphu": "BTN", "Tianjin": "CHN", "Tijuana": "MEX",
  "Tirana": "ALB", "Togliatti": "RUS", "Toulouse": "FRA", "Tripoli": "LBY", "Tunis": "TUN",
  "Turin": "ITA", "Ufa": "RUS", "Ulaanbaatar": "MNG", "Ulsan": "KOR", "Urumqi": "CHN",
  "Vaduz": "LIE", "Valencia": "ESP", "Valletta": "MLT", "Valparaiso": "CHL", "Venice": "ITA",
  "Verona": "ITA", "Victoria": "SYC", "Vientiane": "LAO", "Vilnius": "LTU", "Vladivostok": "RUS",
  "Volgograd": "RUS", "Voronezh": "RUS", "Wellington": "NZL", "Winnipeg": "CAN", "Wuhan": "CHN",
  "Wuxi": "CHN", "Xiamen": "CHN", "Xian": "CHN", "Xining": "CHN", "Xinxiang": "CHN",
  "Yangon": "MMR", "Yaounde": "CMR", "Yekaterinburg": "RUS", "Yerevan": "ARM", "Yokohama": "JPN",
  "Zaragoza": "ESP", "Zhengzhou": "CHN", "Zibo": "CHN", "Zurich": "CHE",
  "Abilene": "USA", "Akron": "USA", "Albany": "USA", "Albuquerque": "USA", "Alexandria": "USA",
  "Allentown": "USA", "Amarillo": "USA", "Anaheim": "USA", "Anchorage": "USA", "Ann Arbor": "USA",
  "Arlington": "USA", "Arvada": "USA", "Asheville": "USA", "Aurora": "USA",
  "Bakersfield": "USA", "Baton Rouge": "USA", "Beaumont": "USA", "Bellevue": "USA", "Berkeley": "USA",
  "Billings": "USA", "Bismarck": "USA", "Boise": "USA", "Boulder": "USA",
  "Bridgeport": "USA", "Brownsville": "USA", "Buffalo": "USA", "Burbank": "USA", "Burlington": "USA",
  "Cambridge": "USA", "Cape Coral": "USA", "Carrollton": "USA", "Cary": "USA", "Cedar Rapids": "USA",
  "Chandler": "USA", "Charleston": "USA", "Charlotte": "USA", "Chattanooga": "USA", "Chesapeake": "USA",
  "Chula Vista": "USA", "Cincinnati": "USA", "Clarksville": "USA", "Clearwater": "USA", "College Station": "USA",
  "Colorado Springs": "USA", "Columbia": "USA", "Concord": "USA", "Coral Springs": "USA",
  "Corona": "USA", "Corpus Christi": "USA", "Costa Mesa": "USA", "Denton": "USA", "Des Moines": "USA",
  "Durham": "USA", "Elizabeth": "USA", "Elk Grove": "USA", "El Paso": "USA", "Eugene": "USA",
  "Evansville": "USA", "Everett": "USA", "Fairfield": "USA", "Fargo": "USA", "Fayetteville": "USA",
  "Fontana": "USA", "Fort Collins": "USA", "Fort Lauderdale": "USA", "Fort Wayne": "USA", "Fort Worth": "USA",
  "Fremont": "USA", "Fresno": "USA", "Fullerton": "USA", "Gainesville": "USA", "Garden Grove": "USA",
  "Garland": "USA", "Gilbert": "USA", "Glendale": "USA", "Grand Prairie": "USA", "Grand Rapids": "USA",
  "Greeley": "USA", "Grand Junction": "USA", "Green Bay": "USA", "Greensboro": "USA", "Gresham": "USA", "Gulfport": "USA",
  "Hartford": "USA", "Hayward": "USA", "Henderson": "USA", "Hialeah": "USA", "High Point": "USA",
  "Hollywood": "USA", "Honolulu": "USA", "Huntington Beach": "USA", "Huntsville": "USA", "Independence": "USA",
  "Indianapolis": "USA", "Inglewood": "USA", "Irvine": "USA", "Irving": "USA", "Jackson": "USA",
  "Jersey City": "USA", "Joliet": "USA", "Kansas City": "USA", "Kent": "USA",
  "Killeen": "USA", "Knoxville": "USA", "Lafayette": "USA", "Lakewood": "USA", "Lancaster": "USA",
  "Lansing": "USA", "Laredo": "USA", "Lexington": "USA", "Lincoln": "USA", "Little Rock": "USA",
  "Long Beach": "USA", "Lowell": "USA", "Lubbock": "USA", "McAllen": "USA", "McKinney": "USA", "Mesa": "USA", "Mesquite": "USA", "Midland": "USA",
  "Miramar": "USA", "Mobile": "USA", "Modesto": "USA", "Montgomery": "USA", "Moreno Valley": "USA",
  "Murfreesboro": "USA", "Naperville": "USA", "New Haven": "USA", "Newark": "USA", "Newport News": "USA",
  "Norfolk": "USA", "Norman": "USA", "North Las Vegas": "USA", "Oceanside": "USA", "Ontario": "USA",
  "Orange": "USA", "Overland Park": "USA", "Oxnard": "USA", "Palm Bay": "USA", "Palmdale": "USA",
  "Pasadena": "USA", "Paterson": "USA", "Pearland": "USA", "Pembroke Pines": "USA", "Peoria": "USA",
  "Plano": "USA", "Pomona": "USA", "Pompano Beach": "USA", "Port St. Lucie": "USA", "Providence": "USA",
  "Provo": "USA", "Raleigh": "USA", "Rancho Cucamonga": "USA", "Reading": "USA", "Redding": "USA",
  "Reno": "USA", "Renton": "USA", "Richardson": "USA", "Riverside": "USA",
  "Rockford": "USA", "Roseville": "USA", "Round Rock": "USA", "Salem": "USA",
  "Salinas": "USA", "Salt Lake City": "USA", "San Bernardino": "USA", "San Buenaventura": "USA", "San Mateo": "USA",
  "Santa Ana": "USA", "Santa Barbara": "USA", "Santa Clara": "USA", "Santa Clarita": "USA", "Santa Rosa": "USA",
  "Savannah": "USA", "Scottsdale": "USA", "Shreveport": "USA", "Simi Valley": "USA", "Sioux Falls": "USA",
  "South Bend": "USA", "Spokane": "USA", "Springfield": "USA", "Stamford": "USA", "Sterling Heights": "USA",
  "Stockton": "USA", "Sunnyvale": "USA", "Syracuse": "USA", "Tacoma": "USA", "Tallahassee": "USA",
  "Tampa": "USA", "Tempe": "USA", "Thornton": "USA", "Thousand Oaks": "USA", "Toledo": "USA",
  "Topeka": "USA", "Torrance": "USA", "Tucson": "USA", "Tulsa": "USA", "Tuscaloosa": "USA",
  "Tyler": "USA", "Vallejo": "USA", "Victorville": "USA", "Visalia": "USA",
  "Warren": "USA", "Waterbury": "USA", "West Covina": "USA", "West Jordan": "USA",
  "West Palm Beach": "USA", "West Valley City": "USA", "Westminster": "USA", "Wichita": "USA", "Wichita Falls": "USA",
  "Wilmington": "USA", "Winston-Salem": "USA", "Worcester": "USA", "Yonkers": "USA",
  "Aberdeen": "GBR", "Belfast": "GBR", "Bristol": "GBR", "Cardiff": "GBR", "Coventry": "GBR",
  "Edinburgh": "GBR", "Leicester": "GBR", "Newcastle": "GBR", "Nottingham": "GBR", "Plymouth": "GBR",
  "Southampton": "GBR", "Swansea": "GBR", "Wolverhampton": "GBR",
  "Adana": "TUR", "Antalya": "TUR", "Konya": "TUR", "Mersin": "TUR",
  "Aarhus": "DNK", "Odense": "DNK", "Aalborg": "DNK",
  "Alicante": "ESP", "Bilbao": "ESP", "Murcia": "ESP", "Palma": "ESP", "Valladolid": "ESP", "Vigo": "ESP",
  "Bari": "ITA", "Bologna": "ITA", "Catania": "ITA", "Florence": "ITA", "Messina": "ITA", "Padua": "ITA", "Trieste": "ITA",
  "Bordeaux": "FRA", "Nantes": "FRA", "Rennes": "FRA", "Saint-Etienne": "FRA",
  "Bremen": "DEU", "Dresden": "DEU", "Duisburg": "DEU", "Hanover": "DEU", "Nuremberg": "DEU",
  "Cork": "IRL", "Galway": "IRL", "Limerick": "IRL",
  "Debrecen": "HUN", "Miskolc": "HUN", "Szeged": "HUN",
  "Espoo": "FIN", "Tampere": "FIN", "Vantaa": "FIN",
  "Gdansk": "POL", "Lodz": "POL", "Lublin": "POL", "Szczecin": "POL", "Wroclaw": "POL",
  "Gothenburg": "SWE", "Malmo": "SWE", "Uppsala": "SWE",
  "Graz": "AUT", "Innsbruck": "AUT", "Klagenfurt": "AUT",
  "Iasi": "ROU", "Cluj-Napoca": "ROU", "Timisoara": "ROU", "Constanta": "ROU", "Craiova": "ROU",
  "Kaunas": "LTU", "Klaipeda": "LTU",
  "Liege": "BEL", "Ghent": "BEL", "Charleroi": "BEL",
  "Plovdiv": "BGR", "Varna": "BGR", "Burgas": "BGR",
  "Turku": "FIN", "Oulu": "FIN", "Jyvaskyla": "FIN",
  "Stavanger": "NOR", "Bergen": "NOR", "Trondheim": "NOR",
  "Nara": "JPN", "Kanazawa": "JPN", "Kagoshima": "JPN",
  "Geneva": "CHE", "Basel": "CHE", "Lausanne": "CHE", "Lucerne": "CHE",
  "Bruges": "BEL", "Leuven": "BEL", "Faro": "PRT", "Coimbra": "PRT", "Braga": "PRT",
  "Edmonton": "CAN", "Perth": "AUS", "Gold Coast": "AUS",
  "Christchurch": "NZL", "Hamilton": "NZL", "Dunedin": "NZL"
};
